spring.application.name=psnf-api

spring.datasource.url=jdbc:postgresql://localhost:5432/psnf
spring.datasource.username=postgres
spring.datasource.password=opentech
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Habilita o virtual threads
spring.threads.virtual.enabled=true

spring.elasticsearch.uris=http://localhost:9200